### PR TITLE
modules: handle multiarch systems' libdir

### PR DESCRIPTION
**Pull request by mochaaP**
- build: fetch gtk-session-lock as a subproject when not present on system
- modules: handle multiarch systems' libdir

### CODE REVIEW

**Comment by jovanlanik** [comment]
Thank you for the PR!

I like the changes to the module handling. Using libdir seems to be correct in meson but I'm not sure I'm happy with the module makefiles (not your fault, it's mine :D). Maybe it would also be best to use meson for building all the modules... I'd merge this and the modules now and will work on meson for the modules.

As for building gtk-session-lock as a subproject, I don't consider the build system the appropriate tool for managing dependencies. I'd prefer to avoid adding this to the build.

**Comment by mochaaP** [comment]
what about making `--wrap-mode=nofallback` default? it's currently a hassle to build gtklock without installing gtk-session-lock globally (e.g. when testing on a new system), so i think it's sensible to include a meson .wrap for this.

**Comment by jovanlanik** [comment]
Yes, that would be acceptable.

Also is there any reason you didn't specify the fallback as `gtk_session_lock = dependency('gtk-session-lock-0', fallback : ['gtk_session_lock', 'gtk_session_lock'])`?

**Comment by mochaaP** [comment]
I would like to keep that in sync with installed pkg-config and make minimal changes to meson.build, so it's done in the .wrap file.

**Comment by jovanlanik** [comment]
Sorry for the delay in merging this.

**Pull request merged**
