### PR TITLE
Introduce meson build system

### PR DESCRIPTION
**Pull request by lujianhua**
Introduce meson build system.
There is two benefits:

1. Generate comple_command.json directly.
2. Meson backend Ninja can improve build speed.

### CODE REVIEW

**Comment by jovanlanik** [comment]
Great work! Out of all the modern build systems meson seems like the sanest option... I only continue to use make because I'm familiar with it.

The build file seems well written (as far as I can tell) and follows examples in the meson docs.

There are two things that still bother me:

- comple_command.json is located in builddir, clangd can't find it by default
- The [wayland module](https://mesonbuild.com/Wayland-module.html) is unstable, might break the build

The second is especially bad, distros depend on the build system to build the packages. Maybe we could replace the module with a custom target?

**Comment by lujianhua** [comment]
> There are two things that still bother me:
> 
>     * comple_command.json is located in builddir, clangd can't find it by default

We can add .clangd to do it. 

>     * The [wayland module](https://mesonbuild.com/Wayland-module.html) is unstable, might break the build
> 
> The second is especially bad, distros depend on the build system to build the packages. Maybe we could replace the module with a custom target?

Yes, replace wayland module with custom target can be done.

**Comment by lujianhua** [comment]
This PR is ready to be merged.

**Comment by jovanlanik** [comment]
Okay, thank you for the contribution! I'll merge to master and the next gtklock release will be using meson.

**Pull request merged**
