### PR TITLE
Make gtklock compilable in FreeBSD

### PR DESCRIPTION
**Pull request by rb-andrade**
Don't know if the quality of the code is ok, it is my first time contributing and I don't have a lot of experience with BSD systems, but I was able to compile and it worked. Also compiled in Linux with no problems.

### CODE REVIEW

**Comment by jovanlanik** [comment]
Thank you for the contribution! I'll try to review this weekend and then hopefully merge it.
I'm curious because you said you don't have much experience with BSD, are you a BSD user yourself?

**Comment by rb-andrade** [comment]
Just started thinkering with it. I've been using Alpine Linux for the last year and changed my sway config to nwg-shell at the beginning of the year. Have just started thinkering with ZFS so I'm dual-booting FreeBSD and Alpine Linux now and trying to learn more FreeBSD. In the process I'm bringing my nwg-shell config from Alpine to FreeBSD.

**Comment by rb-andrade** [comment]
Any specific reason for source.c file not defining _POSIX_C_SOURCE to 200809L as the auth.c file does? Defining this would also solve compatibility with FreeBSD.

**Comment by jovanlanik** [comment]
> Any specific reason for source.c file not defining _POSIX_C_SOURCE to 200809L as the auth.c file does? Defining this would also solve compatibility with FreeBSD.

Sorry I didn't get to reviewing your PR yet.
As for source.c, there isn't any specific reason so if it improves compatibility it can be changed.

**Comment by jovanlanik** [comment]
@rb-andrade Hi, I finally looked over your changes. I cleaned them up a little in the bsd branch, can you check if it still works for you in FreeBSD?

**Pull request merged**
